### ISSUE TITLE
Pushing charts and image to OCI type registry?

### ISSUE THREAD

**Issue by tyagian** [shashankv02/helm-image-mirror#4]
I am trying to push charts and image to Open Container Initiative (OCI) type registry (harbor) but I'm getting 401. 
Do you know if in registries sections I can put destination registry authentication this way,

```
repos:
 #can it use these global credentials for destination registry? 
 #In my use cases, I won't require authentication for source registry but 
 #always for destination will need it. 
  username: "user"
  password: "password"
  add:
  - name: bitnami
    remote: https://charts.bitnami.com/bitnami

charts:
  - repo: bitnami
    name: redis
    fetch: true
    push:
      - harbor
    versions:
        #chart version
      - version: 17.2.0
        fetch: true
registries:
  - name: "harbor.com/helm-image-mirror"
    retain: true
    #(optional) images will not be pushed to the registry if set to false
    push: true
   #can I mention destination credentials under registry name or should I mention these in Global credentials section?
    username: "user"
    password: "password"

```
Executing initialization scripts
Finished executing initialization scripts
Configuring helm repository bitnami
Updating helm repositories
Retagging and pushing images to destinations
Finding images in chart bitnami/redis-17.2.0
Found images: {'docker.io/bitnami/redis:7.0.5-debian-11-r0'}
b'The push refers to repository [harbor.com/helm-image-mirror/redis]\nbb90b94ab891: Preparing\n877c59cba308: Preparing\n' b'unauthorized: unauthorized to access repository: chart-sync/redis, action: push: unauthorized to access repository: chart-sync/redis, action: push\n'
================== Image Status ==================
Traceback (most recent call last):
  File "/usr/local/bin/helm_image_mirror.py", line 829, in <module>
    sys.exit(main(args.config))
  File "/usr/local/bin/helm_image_mirror.py", line 802, in main
    print_dict(
  File "/usr/local/bin/helm_image_mirror.py", line 750, in print_dict
    print(json.dumps(failures, indent=4))
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable

If you see, instead of adding the correct redis version, it's adding gibbrish when pushing image.
